/**
 * Export utilities for PDF, DOCX, and Excel
 * Uses lightweight libraries compatible with Vercel serverless
 */

import type { BOQLineItem, Quotation } from "./types";

/**
 * Generate a printable HTML document for PDF export
 */
export function generateQuotationHTML(
  quotation: Quotation,
  company: { name: string; address?: string | null; gst_number?: string | null; phone?: string | null },
  client: { name: string; address?: string | null; gst_number?: string | null },
  items: BOQLineItem[],
): string {
  const formatCurr = (amount: number) =>
    "₹" + new Intl.NumberFormat("en-IN").format(Math.round(amount));

  const subtotal = items.reduce((s, i) => s + i.amount, 0);
  const profitMargin = (subtotal * (quotation.profit_margin_percent || 0)) / 100;
  const afterProfit = subtotal + profitMargin;
  const discount = quotation.discount_amount || 0;
  const afterDiscount = afterProfit - discount;
  const gst = quotation.gst_amount || 0;

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Quotation ${quotation.quotation_number}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }
  .header { display: flex; justify-content: space-between; border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { color: #2563eb; margin: 0; }
  .company-info, .client-info { font-size: 13px; line-height: 1.6; }
  .company-info .name { font-size: 16px; font-weight: bold; }
  .meta { display: flex; justify-content: space-between; margin-bottom: 24px; font-size: 13px; }
  table { width: 100%; border-collapse: collapse; margin: 16px 0; }
  th { background: #f3f4f6; text-align: left; padding: 8px 12px; font-size: 12px; text-transform: uppercase; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
  td.right { text-align: right; }
  .summary { margin-left: auto; width: 300px; margin-top: 24px; }
  .summary-row { display: flex; justify-content: space-between; padding: 4px 0; font-size: 13px; }
  .summary-row.total { font-weight: bold; font-size: 16px; border-top: 2px solid #2563eb; padding-top: 8px; margin-top: 4px; color: #2563eb; }
  .terms { margin-top: 32px; font-size: 12px; color: #6b7280; }
  .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #9ca3af; }
</style>
</head>
<body>
<div class="header">
  <div>
    <h1>QUOTATION</h1>
    <p style="font-size:13px;color:#6b7280;">${quotation.quotation_number} | Rev ${quotation.revision}</p>
  </div>
  <div class="company-info">
    <div class="name">${company.name}</div>
    ${company.address ? `<div>${company.address}</div>` : ""}
    ${company.gst_number ? `<div>GST: ${company.gst_number}</div>` : ""}
    ${company.phone ? `<div>Phone: ${company.phone}</div>` : ""}
  </div>
</div>

<div class="meta">
  <div class="client-info">
    <strong>To:</strong><br>
    ${client.name}<br>
    ${client.address || ""}
    ${client.gst_number ? `<br>GST: ${client.gst_number}` : ""}
  </div>
  <div style="text-align:right;">
    Date: ${new Date(quotation.created_at).toLocaleDateString("en-IN")}<br>
    Valid Until: ${quotation.valid_until ? new Date(quotation.valid_until).toLocaleDateString("en-IN") : "N/A"}
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Description</th>
      <th class="right">Qty</th>
      <th>Unit</th>
      <th class="right">Rate</th>
      <th class="right">Amount</th>
    </tr>
  </thead>
  <tbody>
    ${items.map((item, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${item.description}</td>
      <td class="right">${item.quantity}</td>
      <td>${item.unit}</td>
      <td class="right">${formatCurr(item.rate)}</td>
      <td class="right">${formatCurr(item.amount)}</td>
    </tr>`).join("")}
  </tbody>
</table>

<div class="summary">
  <div class="summary-row"><span>Subtotal</span><span>${formatCurr(subtotal)}</span></div>
  ${profitMargin > 0 ? `<div class="summary-row"><span>Profit Margin (${quotation.profit_margin_percent}%)</span><span>${formatCurr(profitMargin)}</span></div>` : ""}
  ${discount > 0 ? `<div class="summary-row"><span>Discount (${quotation.discount_percent}%)</span><span>-${formatCurr(discount)}</span></div>` : ""}
  <div class="summary-row"><span>GST (${quotation.gst_percent}%)</span><span>${formatCurr(gst)}</span></div>
  <div class="summary-row total"><span>Grand Total</span><span>${formatCurr(quotation.grand_total)}</span></div>
</div>

${quotation.terms ? `<div class="terms"><strong>Terms & Conditions:</strong><br>${quotation.terms}</div>` : ""}

<div class="footer">
  <p>This is a computer-generated quotation. | Generated by FocusOn AI</p>
</div>
</body>
</html>`;
}
