/**
 * FOI-MeetAI — shared types for the meeting intelligence pipeline.
 * These types intentionally mirror the Google Sheet layout in Section 7
 * of the product spec so that the extractor, verifier, Sheet writer and
 * PDF writer all speak exactly one language.
 */

export type MeetingPlatform = "google_meet" | "zoom" | "ms_teams" | "unknown";

export type SpeakerRole =
  | "client"
  | "pmc"
  | "contractor"
  | "architect"
  | "vendor"
  | "focuson"
  | "unknown";

export type Confidence = "High" | "Medium" | "Low";

export interface Attendee {
  name: string;
  organization?: string;
  role: SpeakerRole | string;
  email?: string;
  /** true when the user confirmed this person in the pre-meeting who's-who form */
  confirmed?: boolean;
}

export interface TranscriptSegment {
  startMs: number;
  endMs: number;
  speakerLabel?: string; // diarization label from STT ("Speaker A" etc.)
  speakerName?: string; // resolved from roster / DOM indicator
  role?: SpeakerRole;
  text: string;
  sttProvider?: string;
  language?: string;
  confidence?: number;
}

/** DOM events captured by platform adapters (who is speaking, chat, captions). */
export interface ContextEvent {
  type: "speaking" | "caption" | "chat" | "participants" | "screen";
  atMs: number;
  name?: string;
  text?: string;
  screenCategory?: string;
  payload?: Record<string, unknown>;
}

/* ---------------------------------- MOM ---------------------------------- */

export interface SourceAnchor {
  /** mm:ss or hh:mm:ss from meeting start */
  sourceTimestamp?: string;
  /** short verbatim quote from the transcript that proves this item */
  sourceQuote?: string;
}

export interface Flagged {
  confidence: Confidence;
  /** set by the /api/verify second pass when an item is not clearly supported */
  verificationFlag?: string;
}

export interface TimelineEntry extends SourceAnchor, Flagged {
  time: string;
  topic: string;
  summary: string;
  screenContext?: string;
}

export interface Decision extends SourceAnchor, Flagged {
  decision: string;
  relatedTo?: string;
  confirmedBy?: string;
}

export interface ActionItem extends SourceAnchor, Flagged {
  owner: string;
  task: string;
  dueDate?: string | null;
  dueDateInferred?: boolean;
  dueDateNote?: string;
  priority: "High" | "Medium" | "Low";
  status: "Pending" | "In Progress" | "Done";
}

export interface Risk extends SourceAnchor, Flagged {
  risk: string;
  impactArea?: string;
  suggestedMitigation?: string; // always labelled "AI Suggestion — confirm with PM"
}

export interface OpenIssue extends SourceAnchor, Flagged {
  issue: string;
  owner?: string;
  targetDate?: string | null;
  targetDateInferred?: boolean;
}

export interface ClientConcern extends SourceAnchor, Flagged {
  concern: string; // verbatim-close quote
  severity: "Critical" | "High" | "Medium" | "Low";
  raisedBy?: string;
  timestamp?: string;
}

export interface Commitment extends SourceAnchor, Flagged {
  who: string;
  promised: string;
}

export interface NextMeeting {
  dateText: string;
  confirmed: boolean;
}

export interface MomDocument {
  projectName: string;
  meetingDate: string; // ISO date
  durationMinutes: number;
  platform: MeetingPlatform | string;
  location?: string;
  preparedBy: string;
  companyName: string;
  attendees: Attendee[];
  agenda: string;
  timeline: TimelineEntry[];
  decisions: Decision[];
  actionItems: ActionItem[];
  risks: Risk[];
  openIssues: OpenIssue[];
  clientConcerns: ClientConcern[];
  commitments: Commitment[];
  nextMeeting: NextMeeting;
  generatedAt: string;
  disclaimer: string;
  /** providers that produced this MOM — written for auditability */
  provenance?: {
    extractionProvider?: string;
    verificationProvider?: string;
    sttProviders?: string[];
  };
  /** full raw transcript is archived with the sheet (hidden tab) */
  transcriptText?: string;
  transcriptSegments?: TranscriptSegment[];
}

export const MOM_DISCLAIMER =
  "Generated by FOI-MeetAI — verify before circulation";

/* ---------------------------- Provider engine ---------------------------- */

export type ProviderTask = "stt" | "llm_extract" | "llm_verify" | "vision";

export type ProviderStatus =
  | "working"
  | "rate_limited"
  | "invalid_key"
  | "unavailable"
  | "not_configured";

export interface ProviderHealthRecord {
  providerId: string;
  task: ProviderTask;
  status: ProviderStatus;
  lastSuccessAt?: string;
  lastFailureAt?: string;
  lastError?: string;
  cooldownUntil?: string;
}

export interface RouteLog {
  at: string;
  task: ProviderTask;
  providerId: string;
  outcome: "success" | "failed" | "skipped_cooldown" | "not_configured";
  errorKind?: string;
  message?: string;
  durationMs?: number;
}

/** Keys collected from the extension / settings screen, keyed by provider id. */
export type UserKeyMap = Record<string, string>;

export interface ProviderContext {
  userKeys: UserKeyMap;
  timeoutMs: number;
  task: ProviderTask;
  log?: (entry: RouteLog) => void;
}
